targets:
    $default:
        builders:
            source_gen:combining_builder:
                options:
                    build_extensions:
                        '^lib/features/{{}}.dart': 'lib/generated/features/{{}}.g.dart'
                        '^lib/core/{{}}.dart': 'lib/generated/core/{{}}.g.dart'