name: nu365
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^8.0.3
  intl: ^0.20.2
  dio: ^5.8.0+1
  go_router: ^15.1.1
  flutter_bloc: ^9.1.0
  google_fonts: ^6.2.1
  objectbox: ^4.2.0
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  flutter_svg: ^2.1.0
  sqflite: ^2.4.2
  image_picker: ^1.0.7
  camera: ^0.11.1
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.2
  path: ^1.8.3
  supabase_flutter: ^2.8.4
  mime: ^2.0.0
  fl_chart: ^1.0.0
  skeletonizer: ^1.4.3
  flutter_launcher_icons: ^0.14.3
  otp_pin_field: ^1.4.1
  url_launcher: ^6.3.1  
  local_auth: ^2.3.0
  device_info_plus: ^11.4.0
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_dotenv: ^5.2.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_logo.png"
  min_sdk_android: 21 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - .env

