name: nu365
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^8.0.3
  intl: ^0.20.2
  dio: ^5.8.0+1
  go_router: ^15.1.1
  flutter_bloc: ^9.1.0
  google_fonts: ^6.2.1
  objectbox: ^4.2.0
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

